name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/docs.yml"
      - "docs/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/docs.yml"
      - "docs/**"

jobs:
  ci-latest-tag:
    uses: ./.github/workflows/shared.yml
    with:
      lsp_use_latest_tag: true

  ci-latest-commit:
    uses: ./.github/workflows/shared.yml
    with:
      lsp_use_latest_tag: false
