name: Test on LSP change

on:
  repository_dispatch:
    types:
      - new_release
      - new_commit

jobs:
  ci-latest-tag:
    if: github.event.action == 'new_release'
    uses: ./.github/workflows/shared.yml

  ci-latest-commit:
    if: github.event.action == 'new_commit'
    uses: ./.github/workflows/shared.yml
    with:
      lsp_use_latest_tag: false
